import type { Category, Event, PlatformStats, User } from '@/types';
import { CORE_CATEGORIES } from '@/lib/categories';

export const SEED_EVENTS: Event[] = [
  {
    id: 1,
    title: 'Festival de Música Eletrônica 2026',
    description:
      'O maior festival de música eletrônica da região com DJs internacionais e nacionais.',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
    category: 'Música',
    date: '2026-06-15',
    time: '20:00',
    location: 'Parque Villa-Lobos, São Paulo - SP',
    organizer: 'Maria Silva',
    organizerId: 1,
    price: 150,
    capacity: 5000,
    confirmed: 3420,
    status: 'upcoming',
    rating: 4.8,
    reviews: 234,
    featured: true,
  },
  {
    id: 2,
    title: 'Tech Summit Brazil 2026',
    description:
      'Conferência anual sobre tecnologia, inovação e transformação digital.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    category: 'Tecnologia',
    date: '2026-07-20',
    time: '09:00',
    location: 'Centro de Convenções Frei Caneca, São Paulo - SP',
    organizer: 'João Santos',
    organizerId: 2,
    price: 300,
    capacity: 1000,
    confirmed: 847,
    status: 'upcoming',
    rating: 4.9,
    reviews: 156,
    featured: true,
  },
  {
    id: 3,
    title: 'Maratona de São Paulo',
    description:
      'Corrida oficial de 42km pelas principais avenidas da cidade.',
    image: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800',
    category: 'Esportes',
    date: '2026-08-10',
    time: '06:00',
    location: 'Av. Paulista, São Paulo - SP',
    organizer: 'Carlos Oliveira',
    organizerId: 3,
    price: 80,
    capacity: 30000,
    confirmed: 28500,
    status: 'upcoming',
    rating: 4.7,
    reviews: 892,
    featured: true,
  },
  {
    id: 4,
    title: 'Workshop: React Avançado',
    description: 'Aprenda técnicas avançadas de React com instrutores certificados.',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
    category: 'Tecnologia',
    date: '2026-05-30',
    time: '14:00',
    location: 'Campus Tech Hub, São Paulo - SP',
    organizer: 'Maria Silva',
    organizerId: 1,
    price: 250,
    capacity: 50,
    confirmed: 45,
    status: 'upcoming',
    rating: 5.0,
    reviews: 32,
    featured: false,
  },
  {
    id: 5,
    title: 'Copa de Futebol Amador',
    description: 'Torneio comunitário com times amadores de toda a região.',
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
    category: 'Esportes',
    date: '2026-06-20',
    time: '09:00',
    location: 'Estádio do Pacaembu, São Paulo - SP',
    organizer: 'Carlos Oliveira',
    organizerId: 3,
    price: 0,
    capacity: 5000,
    confirmed: 1200,
    status: 'upcoming',
    rating: 4.6,
    reviews: 89,
    featured: false,
  },
  {
    id: 6,
    title: 'Show Acústico ao Vivo',
    description: 'Noite especial com artistas nacionais em formato intimista.',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    category: 'Música',
    date: '2026-06-08',
    time: '21:00',
    location: 'Teatro Municipal, São Paulo - SP',
    organizer: 'Maria Silva',
    organizerId: 1,
    price: 120,
    capacity: 800,
    confirmed: 650,
    status: 'upcoming',
    rating: 4.9,
    reviews: 112,
    featured: false,
  },
];

export const SEED_CATEGORIES: Category[] = CORE_CATEGORIES;

export const SEED_PLATFORM_STATS: PlatformStats = {
  totalEvents: 1247,
  totalUsers: 45632,
  totalOrganizers: 892,
  eventsThisMonth: 156,
  averageRating: 4.7,
  totalRevenue: 'R$ 2.8M',
  growthRate: '+23%',
};

export const SEED_USERS: Omit<User, 'id'>[] = [
  {
    name: 'Maria Silva',
    email: 'maria@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    role: 'organizer',
    bio: 'Produtora de eventos há 10 anos. Especializada em festivais de música.',
    eventsCreated: 12,
    eventsAttended: 45,
    rating: 4.8,
    interests: ['Música', 'Tecnologia'],
  },
  {
    name: 'João Santos',
    email: 'joao@example.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    role: 'organizer',
    bio: 'Empresário do setor tech. Organizador de conferências e meetups.',
    eventsCreated: 8,
    eventsAttended: 67,
    rating: 4.9,
    interests: ['Tecnologia', 'Esportes'],
  },
  {
    name: 'Carlos Oliveira',
    email: 'carlos@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    role: 'organizer',
    bio: 'Ex-atleta profissional. Organizador de eventos esportivos comunitários.',
    eventsCreated: 15,
    eventsAttended: 23,
    rating: 4.7,
    interests: ['Esportes', 'Música'],
  },
  {
    name: 'Admin EventHub',
    email: 'admin@eventhub.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    role: 'admin',
    bio: 'Administrador da plataforma EventHub.',
    eventsCreated: 0,
    eventsAttended: 0,
    rating: 5.0,
    interests: ['Música', 'Tecnologia', 'Esportes'],
  },
];

export const DEMO_PASSWORD = 'demo123';
